# Generated by Django 4.1.7 on 2023-03-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(max_length=50)),
                ('stars', models.IntegerField(max_length=50)),
                ('languges', models.CharField(max_length=50)),
            ],
        ),
    ]
