# Generated by Django 4.1.7 on 2023-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubstatitics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repotable',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repotable',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
